model:
  learning_task: NODE_CLASSIFICATION
  encoder:
#    use_hashmap_sets: true
    use_incoming_nbrs: true
    use_outgoing_nbrs: true
    layers:
      - train_neighbor_sampling:
          type: UNIFORM
          options:
            max_neighbors: 5
        eval_neighbor_sampling:
          type: UNIFORM
          options:
            max_neighbors: 5
        init:
          type: GLOROT_NORMAL
        type: GRAPH_SAGE
        options:
          input_dim: 128
          output_dim: 128
          aggregator: MEAN
        bias: true
        bias_init:
          type: ZEROS
        activation: RELU
      - train_neighbor_sampling:
          type: UNIFORM
          options:
            max_neighbors: 4
        eval_neighbor_sampling:
          type: UNIFORM
          options:
            max_neighbors: 4
        init:
          type: GLOROT_NORMAL
        type: GRAPH_SAGE
        options:
          input_dim: 128
          output_dim: 128
          aggregator: MEAN
        bias: true
        bias_init:
          type: ZEROS
        activation: RELU
      - train_neighbor_sampling:
          type: UNIFORM
          options:
            max_neighbors: 3
        eval_neighbor_sampling:
          type: UNIFORM
          options:
            max_neighbors: 3
        init:
          type: GLOROT_NORMAL
        type: GRAPH_SAGE
        options:
          input_dim: 128
          output_dim: 40
          aggregator: MEAN
        bias: true
        bias_init:
          type: ZEROS
        activation: NONE
    optimizer:
      type: ADAM
      options:
        learning_rate: 0.003
storage:
  device_type: cuda
  dataset:
    base_directory: datasets/karate/
    num_edges: 156
    num_nodes: 35
    num_relations: 1
    num_train: 10
    num_valid: 10
    num_test: 15
    feature_dim: 128
    num_classes: 40
  edges:
    type: FLAT_FILE
  nodes:
    type: HOST_MEMORY
  features:
    type: PARTITION_BUFFER
    options:
      num_partitions: 9
      buffer_capacity: 5
      prefetching: true
      fine_to_coarse_ratio: 1
      num_cache_partitions: 0
      node_partition_ordering: SEQUENTIAL
  prefetch: true
  shuffle_input: true
  full_graph_evaluation: true
training:
  batch_size: 3
  num_epochs: 1
  pipeline:
    sync: true
  epochs_per_shuffle: 1
  logs_per_epoch: 10
evaluation:
  batch_size: 3
  pipeline:
    sync: true
  epochs_per_eval: 1